### ISSUE TITLE
Discuss: Cannot `export ... from ...` dynamic modules

### ISSUE THREAD

**Issue by bmeck** [tc39/proposal-dynamic-modules#1]
https://github.com/caridy/proposal-dynamic-modules/blob/d8160a6137e6b878cb7f09b82404df0973980cfd/spec.emu#L75

> Assert: If M is a Source Text Module Record, then M.[[Environment]] has a direct binding for N2.

This would mean that if `M` uses `export {foo} from "bar";` and `bar` is dynamic, it would fail. I assume this is expected / we should throw an error?

**Comment by caridy** [comment]
No. `export ... from ...` will never trigger `CreateImportBinding` because it is resolved. To be specific, if you have:

A (ESM) -> B (ESM) -> C (CJS) 

If A imports something from B that is re-exported from C, then the binding will go from A to C directly due the resolution process in `ResolveExport`, it is not going to go through multiple bindings.
